# Path to the file where player accounts will be stored
accounts_file_name = "plugins/DiscordAuth/accounts.json"

# Server lobby name
lobby_server = "lobby"

# Lifetime in seconds of the key and session, respectively
key_expiration_time = 60
session_expiration_time = 60

# Discord bot token
bot_token = ""

# Auth first message
auth_first_message = "<#F8554B>Please login first"

# Missing account message
missing_account_message = "Account missing!"

# Send a key message, where %key% is the key itself
send_key_message = "Send key <#16D886><click:copy_to_clipboard:%key%><hover:show_text:'Copy'>%key%</hover></click><reset> to Clown#1672 bot"

# Session restored message
session_restored_message = "<#16D886>Session restored"

# Successful auth message
successful_auth_message = "<#16D886>Successful auth"

# Successful auth discord message
successful_auth_discord_message = "You are successfully logged in :white_check_mark:"

# Invalid key message
invalid_key_message = "Invalid key"

# Key not found
key_not_found = "Key not found"
