# Path to the file where player accounts will be stored
accounts_file_name = "plugins/DiscordAuth/accounts.json"

# Server lobby name
lobby_server = "lobby"

# Lifetime in seconds of the key and session, respectively
key_expiration_time = 60
session_expiration_time = 60

# Discord bot token
bot_token = ""
