[minecraft]
invalid_command_syntax = "Invalid command syntax"

account_already_exists = "Account already exists"
account_with_that_name_already_exists = "Account with that name already exists"
account_with_that_discord_id_already_exists = "Account with that Discord ID already exists"

account_added = "Account successful added"
account_removed = "Account successful removed"

config_reloaded = "Config successfully reloaded"
messages_reloaded = "Messages successfully reloaded"

session_restored = "<#78B159>Session successfully restored"

missing_account = "<#DD2E46>Missing account"

successful_auth = "<#78B159>Successful auth"

send_key = "Send key <#5865F2><click:copy_to_clipboard:%key%><hover:show_text:'Copy'>%key%</hover></click><reset> to <#5865F2>DiscordAuth#0000<reset> bot"

auth_first = "<#DD2E46>Please auth first"

[discord]
account_with_that_name_already_exists = "Account with that name already exists"
account_with_that_discord_id_already_exists = "Account with that Discord ID already exists"

missing_account = ":red_square: Missing account"

invalid_key = "Invalid key"
key_not_found = "Key not found"

successful_auth = ":green_square: Successful auth"
